# Generated by Django 3.1.3 on 2020-11-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SP', 'sales Person'), ('PH', 'Production Head'), ('Ac', 'Accountant'), ('SM', 'Service Manager'), ('STM', 'Store Manager')], default='green', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=10, verbose_name='phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CK_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RN', models.CharField(blank=True, max_length=100, null=True)),
                ('QUERY_ID', models.CharField(blank=True, max_length=300, null=True)),
                ('QTYPE', models.CharField(blank=True, max_length=300, null=True)),
                ('SENDERNAME', models.CharField(blank=True, max_length=300, null=True)),
                ('SENDEREMAIL', models.CharField(blank=True, max_length=300, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=2000, null=True)),
                ('DATE_RE', models.CharField(blank=True, max_length=300, null=True)),
                ('DATE_R', models.CharField(blank=True, max_length=300, null=True)),
                ('DATE_TIME_RE', models.CharField(blank=True, max_length=300, null=True)),
                ('GLUSR_USR_COMPANYNAME', models.CharField(blank=True, max_length=1000, null=True)),
                ('READ_STATUS', models.CharField(blank=True, max_length=300, null=True)),
                ('SENDER_GLUSR_USR_ID', models.CharField(blank=True, max_length=300, null=True)),
                ('MOB', models.CharField(blank=True, max_length=300, null=True)),
                ('COUNTRY_FLAG', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('QUERY_MODID', models.CharField(blank=True, max_length=300, null=True)),
                ('LOG_TIME', models.CharField(blank=True, max_length=300, null=True)),
                ('QUERY_MODREFID', models.CharField(blank=True, max_length=300, null=True)),
                ('DIR_QUERY_MODREF_TYPE', models.CharField(blank=True, max_length=300, null=True)),
                ('ORG_SENDER_GLUSR_ID', models.CharField(blank=True, max_length=300, null=True)),
                ('ENQ_MESSAGE', models.CharField(blank=True, max_length=2030, null=True)),
                ('ENQ_ADDRESS', models.CharField(blank=True, max_length=2000, null=True)),
                ('ENQ_CALL_DURATION', models.CharField(blank=True, max_length=300, null=True)),
                ('ENQ_RECEIVER_MOB', models.CharField(blank=True, max_length=300, null=True)),
                ('ENQ_CITY', models.CharField(blank=True, max_length=300, null=True)),
                ('ENQ_STATE', models.CharField(blank=True, max_length=300, null=True)),
                ('PRODUCT_NAME', models.CharField(blank=True, max_length=300, null=True)),
                ('COUNTRY_ISO', models.CharField(blank=True, max_length=300, null=True)),
                ('EMAIL_ALT', models.CharField(blank=True, max_length=300, null=True)),
                ('MOBILE_ALT', models.CharField(blank=True, max_length=300, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=300, null=True)),
                ('PHONE_ALT', models.CharField(blank=True, max_length=300, null=True)),
                ('IM_MEMBER_SINCE', models.CharField(blank=True, max_length=300, null=True)),
                ('TOTAL_COUNT', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
