# Generated by Django 3.1.3 on 2020-11-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='phone number'),
        ),
    ]
