# Generated by Django 3.1.3 on 2020-11-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0002_auto_20201117_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
