# Generated by Django 3.1.3 on 2020-11-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0002_auto_20201108_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('MobNum', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
