# Generated by Django 3.1.3 on 2020-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0004_auto_20201109_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='MobNum',
            field=models.CharField(max_length=10),
        ),
    ]
