# Generated by Django 3.1.3 on 2020-11-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0004_auto_20201126_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ck_account',
            name='Visit_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.client_visit'),
        ),
    ]
