# Generated by Django 3.1.3 on 2020-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0005_auto_20201109_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ck_account',
            name='COUNTRY_FLAG',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='COUNTRY_ISO',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='DATE_R',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='DATE_RE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='DATE_TIME_RE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='DIR_QUERY_MODREF_TYPE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='EMAIL_ALT',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_ADDRESS',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_CALL_DURATION',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_CITY',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_MESSAGE',
            field=models.CharField(blank=True, max_length=2030, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_RECEIVER_MOB',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ENQ_STATE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='GLUSR_USR_COMPANYNAME',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='IM_MEMBER_SINCE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='LOG_TIME',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='MOB',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='MOBILE_ALT',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='ORG_SENDER_GLUSR_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='PHONE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='PHONE_ALT',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='PRODUCT_NAME',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='QTYPE',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='QUERY_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='QUERY_MODID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='QUERY_MODREFID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='READ_STATUS',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='RN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='SENDEREMAIL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='SENDERNAME',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='SENDER_GLUSR_USR_ID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='SUBJECT',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ck_account',
            name='TOTAL_COUNT',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
