# Generated by Django 3.1.3 on 2020-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0005_auto_20201126_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='ck_account',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
