# Generated by Django 3.1.3 on 2020-11-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0006_ck_account_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ck_account',
            name='visited_status',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
    ]
