# Generated by Django 3.1.3 on 2020-11-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0006_auto_20201109_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='ck_account',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.userreg', verbose_name='username'),
        ),
    ]
